/**
 * World 1: Neon Stack (Levels 1–10)
 * Visual theme: Deep Purple / Sunset Glow
 */

import { OBJECTIVE_TYPES } from '../game/objectives.js';

export const WORLD_1_LEVELS = [
  {
    id: 1,
    world: 1,
    worldName: 'Neon Stack',
    name: 'First Shift',
    gravityMultiplier: 1.0,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 8,
    },
    star2Score: 2500,
    star3Score: 4500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clear 8 lines to stabilize the matrix.',
  },
  {
    id: 2,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Cadence',
    gravityMultiplier: 1.1,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 12,
    },
    star2Score: 4000,
    star3Score: 7000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clear 12 lines with increased piece flow.',
  },
  {
    id: 3,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Score Drive',
    gravityMultiplier: 1.15,
    objective: {
      type: OBJECTIVE_TYPES.REACH_SCORE,
      target: 3000,
    },
    star2Score: 4500,
    star3Score: 6500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Reach 3,000 points using doubles and drops.',
  },
  {
    id: 4,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Twin Lines',
    gravityMultiplier: 1.2,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 14,
    },
    star2Score: 5000,
    star3Score: 8000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Focus on multi-line clears to speed up progress.',
  },
  {
    id: 5,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Combo Sparks',
    gravityMultiplier: 1.25,
    objective: {
      type: OBJECTIVE_TYPES.COMBO_TARGET,
      target: 3,
    },
    star2Score: 4000,
    star3Score: 7500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Build a combo chain of at least x3.',
  },
  {
    id: 6,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Pace Shift',
    gravityMultiplier: 1.35,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 15,
    },
    star2Score: 6000,
    star3Score: 9000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clear 15 lines under faster gravity.',
  },
  {
    id: 7,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Endurance Stack',
    gravityMultiplier: 1.3,
    objective: {
      type: OBJECTIVE_TYPES.SURVIVE_PIECES,
      target: 35,
    },
    star2Score: 5500,
    star3Score: 8500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Place 35 pieces safely without topping out.',
  },
  {
    id: 8,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Quad Precision',
    gravityMultiplier: 1.25,
    objective: {
      type: OBJECTIVE_TYPES.QUAD_CLEAR,
      target: 1,
    },
    star2Score: 4000,
    star3Score: 7000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Set up an I-piece slot and perform a Quad clear.',
  },
  {
    id: 9,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Debris Field',
    gravityMultiplier: 1.3,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 12,
    },
    star2Score: 5000,
    star3Score: 8500,
    startingGarbage: 2,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clean up 2 starting garbage rows and clear 12 lines.',
  },
  {
    id: 10,
    world: 1,
    worldName: 'Neon Stack',
    name: 'Pulse Trial I',
    gravityMultiplier: 1.5,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 20,
    },
    star2Score: 9000,
    star3Score: 14000,
    startingGarbage: 2,
    risingGarbageEveryPieces: 16,
    timeLimitMs: null,
    isPulseTrial: true,
    description: 'World 1 Boss Trial: Rising garbage and rapid gravity!',
  },
];
