/**
 * World 2: Shift Circuit (Levels 11–20)
 * Visual theme: Cyan / Emerald Neon
 */

import { OBJECTIVE_TYPES } from '../game/objectives.js';

export const WORLD_2_LEVELS = [
  {
    id: 11,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Circuit Gate',
    gravityMultiplier: 1.55,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 14,
    },
    star2Score: 6000,
    star3Score: 10000,
    startingGarbage: 1,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Welcome to World 2: Higher baseline tempo and narrow matrix.',
  },
  {
    id: 12,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Time Surge',
    gravityMultiplier: 1.6,
    objective: {
      type: OBJECTIVE_TYPES.TIME_ATTACK,
      target: 10,
    },
    star2Score: 5000,
    star3Score: 8500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: 90000, // 90 seconds
    description: 'Clear 10 lines before the 90-second countdown runs out.',
  },
  {
    id: 13,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Double Quad',
    gravityMultiplier: 1.6,
    objective: {
      type: OBJECTIVE_TYPES.QUAD_CLEAR,
      target: 2,
    },
    star2Score: 7000,
    star3Score: 11000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Stack high and execute 2 Quad clears.',
  },
  {
    id: 14,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Chain Reactor',
    gravityMultiplier: 1.65,
    objective: {
      type: OBJECTIVE_TYPES.COMBO_TARGET,
      target: 4,
    },
    star2Score: 8000,
    star3Score: 12000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Form a massive 4-step combo chain.',
  },
  {
    id: 15,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Efficiency Test',
    gravityMultiplier: 1.7,
    objective: {
      type: OBJECTIVE_TYPES.LIMITED_PIECES,
      target: 12,
      maxPieces: 32,
    },
    star2Score: 6500,
    star3Score: 10500,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clear 12 lines using at most 32 pieces.',
  },
  {
    id: 16,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Garbage Rising',
    gravityMultiplier: 1.75,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 16,
    },
    star2Score: 8500,
    star3Score: 13500,
    startingGarbage: 2,
    risingGarbageEveryPieces: 14,
    timeLimitMs: null,
    description: 'New garbage row rises every 14 pieces placed.',
  },
  {
    id: 17,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Score Overload',
    gravityMultiplier: 1.8,
    objective: {
      type: OBJECTIVE_TYPES.REACH_SCORE,
      target: 8000,
    },
    star2Score: 11000,
    star3Score: 16000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Score 8,000 points using combo multipliers and hard drops.',
  },
  {
    id: 18,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Back-to-Back Spark',
    gravityMultiplier: 1.85,
    objective: {
      type: OBJECTIVE_TYPES.BACK_TO_BACK,
      target: 2,
    },
    star2Score: 9000,
    star3Score: 14000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Execute 2 consecutive Quad clears (Back-to-Back).',
  },
  {
    id: 19,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Trench Defense',
    gravityMultiplier: 1.9,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 18,
    },
    star2Score: 10000,
    star3Score: 15500,
    startingGarbage: 3,
    risingGarbageEveryPieces: 15,
    timeLimitMs: null,
    description: '3 starting garbage rows and high-speed gravity.',
  },
  {
    id: 20,
    world: 2,
    worldName: 'Shift Circuit',
    name: 'Pulse Trial II',
    gravityMultiplier: 2.1,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 25,
    },
    star2Score: 14000,
    star3Score: 21000,
    startingGarbage: 3,
    risingGarbageEveryPieces: 12,
    timeLimitMs: null,
    isPulseTrial: true,
    description: 'World 2 Boss Trial: Relentless rising garbage and hyper gravity!',
  },
];
