/**
 * World 3: Gravity Core (Levels 21–30)
 * Visual theme: Violet / Crimson / Core White
 */

import { OBJECTIVE_TYPES } from '../game/objectives.js';

export const WORLD_3_LEVELS = [
  {
    id: 21,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Event Horizon',
    gravityMultiplier: 2.2,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 18,
    },
    star2Score: 10000,
    star3Score: 16000,
    startingGarbage: 2,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Entering the Core: Ultra high baseline gravity.',
  },
  {
    id: 22,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Flash Clear',
    gravityMultiplier: 2.3,
    objective: {
      type: OBJECTIVE_TYPES.TIME_ATTACK,
      target: 15,
    },
    star2Score: 8000,
    star3Score: 13000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: 75000, // 75 seconds
    description: 'Clear 15 lines under intense 75-second timer.',
  },
  {
    id: 23,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Triple Quad Core',
    gravityMultiplier: 2.35,
    objective: {
      type: OBJECTIVE_TYPES.QUAD_CLEAR,
      target: 3,
    },
    star2Score: 12000,
    star3Score: 19000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Land 3 Quads under extreme falling speed.',
  },
  {
    id: 24,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Hyper Combo',
    gravityMultiplier: 2.4,
    objective: {
      type: OBJECTIVE_TYPES.COMBO_TARGET,
      target: 5,
    },
    star2Score: 13000,
    star3Score: 20000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Achieve an astounding x5 combo streak.',
  },
  {
    id: 25,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Core Compression',
    gravityMultiplier: 2.5,
    objective: {
      type: OBJECTIVE_TYPES.LIMITED_PIECES,
      target: 16,
      maxPieces: 36,
    },
    star2Score: 11000,
    star3Score: 17000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Clear 16 lines using only 36 pieces.',
  },
  {
    id: 26,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Singularity Drift',
    gravityMultiplier: 2.6,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 20,
    },
    star2Score: 14000,
    star3Score: 22000,
    startingGarbage: 3,
    risingGarbageEveryPieces: 10,
    timeLimitMs: null,
    description: 'Fast rising garbage every 10 pieces placed.',
  },
  {
    id: 27,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Grand Back-to-Back',
    gravityMultiplier: 2.7,
    objective: {
      type: OBJECTIVE_TYPES.BACK_TO_BACK,
      target: 3,
    },
    star2Score: 16000,
    star3Score: 25000,
    startingGarbage: 0,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Execute 3 consecutive Back-to-Back Quads.',
  },
  {
    id: 28,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Score Critical',
    gravityMultiplier: 2.8,
    objective: {
      type: OBJECTIVE_TYPES.REACH_SCORE,
      target: 15000,
    },
    star2Score: 20000,
    star3Score: 30000,
    startingGarbage: 2,
    risingGarbageEveryPieces: null,
    timeLimitMs: null,
    description: 'Amass 15,000 points under maximum pressure.',
  },
  {
    id: 29,
    world: 3,
    worldName: 'Gravity Core',
    name: 'Final Approach',
    gravityMultiplier: 2.9,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 24,
    },
    star2Score: 18000,
    star3Score: 28000,
    startingGarbage: 4,
    risingGarbageEveryPieces: 12,
    timeLimitMs: null,
    description: '4 starting garbage rows and near-instant drop speed.',
  },
  {
    id: 30,
    world: 3,
    worldName: 'Gravity Core',
    name: 'FINAL SHIFT TRIAL',
    gravityMultiplier: 3.2,
    objective: {
      type: OBJECTIVE_TYPES.CLEAR_LINES,
      target: 30,
    },
    star2Score: 25000,
    star3Score: 40000,
    startingGarbage: 4,
    risingGarbageEveryPieces: 8,
    timeLimitMs: null,
    isPulseTrial: true,
    description: 'The Ultimate Trial: Stabilize the Gravity Core and complete the campaign!',
  },
];
